apiVersion: v1
kind: Deployment
metadata:
  name: ${project.artifactId}
spec:
  template:
    spec:
      containers:
        - env:
          - name: EUREKA_PORT
            valueFrom:
              configMapKeyRef:
                name: eureka-config
                key: eureka.port
          - name: JAVA_OPTIONS
            value: "-Dspring.profiles.active=openshift"