server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/

zuul:
  routes:
    weather-service:
      path: /weather/**
      serviceId: weather-app
    car-service:
      path: /car/**
      serviceId: car-app
    frontend-app:
      path: /frontend/**
      serviceId: frontend-app
