apiVersion: v1
kind: Deployment
metadata:
  name: ${project.artifactId}
spec:
  template:
    spec:
      containers:
      - env:
        - name: EUREKA_PORT
          valueFrom:
            configMapKeyRef:
              name: eureka-config
              key: eureka.port
        - name: EUREKA_HOST
          valueFrom:
            configMapKeyRef:
              name: eureka-config
              key: eureka.host
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: car-config
              key: host
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: car-config
              key: port
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: car-config
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: car-config
              key: password
        - name: JAVA_OPTIONS
          value: "-Dspring.profiles.active=openshift"