spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/javahippie/spring-cloud-demo-config.git
  application:
    name: auth-service

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/