spring:
  application:
    name: car-app
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: tbd
    username: tbd
    password: tbd

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/