spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/javahippie/spring-cloud-demo-config.git
  application:
    name: config-service

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/